title: Air !!!
author: Deng Junqiang
email: sh109419@163.com
description: > 
  Air !!! is a free iOS App that notify air pollution, provide AQI query & AQI forecast

show_excerpts: false # set to true to show excerpts on the homepage

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.md

# Build settings
theme: jekyll-theme-slate
